/**
 * filelinks root configuration
 * This file references all link files in the repository
 * Generated by: filelinks init
 */

// import { RootConfig } from 'filelinks';
import { RootConfig } from './src/types';

const config: RootConfig = {
  linkFiles: [
    {
      id: 'working-test',
      name: 'Working Test Links',
      path: './cli_test/working/filelinks.links.json',
    },
    {
      id: 'examples',
      name: 'Examples Links',
      path: 'examples/filelinks.links.json',
    },
    {
      id: 'examples',
      name: 'Examples Links Same ID',
      path: 'examples/filelinks.links.json',
    },
    {
      id: 'cli-test',
      name: 'CLI Test Links',
      path: './cli_test/filelinks.links.json',
    },
    {
      id: 'cli-test-duplicate',
      name: 'CLI Test Links Duplicate',
      path: './cli_test/filelinks.links.json',
    },
    {
      id: 'cli-test',
      name: 'CLI Test Links Duplicate with Same ID',
      path: './cli_test/filelinks.links.json',
    },
    {
      id: 'invalid-path-to-links-file',
      name: 'Invalid Path to Links File',
      path: './path/to/nowhere/filelinks.links.json',
    },
    {
      id: 'path-to-folder-instead-of-file',
      name: 'Path to Folder Instead of File',
      path: './cli_test',
    },
    {
      id: 'path-to-invalid-folder',
      name: 'Path to Invalid Folder',
      path: './path/to/nowhere',
    },
    {
      id: 'path-to-invalid-file',
      name: 'Path to Invalid File',
      path: './cli_test/invalid-file.txt',
    },
    {
      id: 'path-to-parent-folder',
      name: 'Path to Parent Folder',
      path: '../.',
    },
    {
      id: 'path-to-parent-links-file',
      name: 'Path to Parent Links File',
      path: '../filelinks.links.json',
    },
    // {
    //   id: 'no-path-provided',
    //   name: 'No Path Provided',
    // },
    {
      id: 'empty-path',
      name: 'Empty Path',
      path: '',
    },
    // {
    //   name: 'No ID Provided',
    //   path: './cli_test/filelinks.links.json',
    // },
    {
      id: '',
      name: 'Empty ID',
      path: './cli_test/filelinks.links.json',
    },
    {
      id: '',
      name: '',
      path: '',
    },
    // {},
    {
      id: 'empty-link-file',
      name: 'Empty Link File',
      path: './cli_test/empty_link_file/filelinks.links.json',
    },
    {
      id: 'empty-links-array',
      name: 'Empty Links Array',
      path: './cli_test/empty_links_array/filelinks.links.json',
    },
  ],
};

export default config;
